simplifying devcontainer dockerfile and adding azure cli

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -3,54 +3,45 @@
 # Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
 #-------------------------------------------------------------------------------------------------------------
 
-FROM golang:1.13.10
+FROM golang:1.13.10-buster
 
-# This Dockerfile adds a non-root user with sudo access. Use the "remoteUser"
-# property in devcontainer.json to use it. On Linux, the container user's GID/UIDs
-# will be updated to match your local UID/GID (when using the dockerFile property).
-# See https://aka.ms/vscode-remote/containers/non-root-user for details.
-ARG USERNAME=vscode
-ARG USER_UID=1000
-ARG USER_GID=$USER_UID
-
-# Docker script args, location, and expected SHA - SHA generated on release
-ARG DOCKER_SCRIPT_SOURCE="https://raw.githubusercontent.com/microsoft/vscode-dev-containers/master/script-library/docker-debian.sh"
-ARG DOCKER_SCRIPT_SHA="dev-mode"
-ARG ENABLE_NONROOT_DOCKER="true"
-ARG SOURCE_SOCKET=/var/run/docker-host.sock
-ARG TARGET_SOCKET=/var/run/docker.sock
-
-# Configure apt, install packages and tools
-RUN apt-get update \
-    && export DEBIAN_FRONTEND=noninteractive \
-    && apt-get -y install --no-install-recommends apt-utils dialog 2>&1 \
+# Configure apt, install packages and cli tools
+RUN export DEBIAN_FRONTEND=noninteractive \
+    && apt-get update \
+    && apt-get -y install --no-install-recommends apt-transport-https ca-certificates curl gnupg2 lsb-release \
+    # 
+    # Install Kubebuilder
+    && curl -sL https://go.kubebuilder.io/dl/2.3.1/$(go env GOOS)/$(go env GOARCH) | tar -xz --strip-components=2 -C /usr/local/bin \
     #
-    # Verify git, process tools, lsb-release (common in install instructions for CLIs) installed
-    && apt-get -y install git openssh-client curl less iproute2 procps lsb-release \
+    # Install Helm
+    && curl -s https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz | tar -zxv --strip-components=1 -C /usr/local/bin linux-amd64/helm \
     #
-    # Create a non-root user to use if not already available - see https://aka.ms/vscode-remote/containers/non-root-user.
-    && if [ $(getent passwd $USERNAME) ]; then \
-        # If exists, see if we need to tweak the GID/UID
-        if [ "$USER_GID" != "1000" ] || [ "$USER_UID" != "1000" ]; then \
-            groupmod --gid $USER_GID $USERNAME \
-            && usermod --uid $USER_UID --gid $USER_GID $USERNAME \
-            && chown -R $USER_UID:$USER_GID /home/$USERNAME; \
-        fi; \
-    else \
-        # Otherwise ccreate the non-root user
-        groupadd --gid $USER_GID $USERNAME \
-        && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
-        # Add sudo support for the non-root user
-        && apt-get install -y sudo \
-        && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
-        && chmod 0440 /etc/sudoers.d/$USERNAME; \
-    fi \
+    # Install Docker CLI package source
+    && curl -fsSL https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/gpg | (OUT=$(apt-key add - 2>&1) || echo $OUT) \
+    && echo "deb [arch=amd64] https://download.docker.com/linux/$(lsb_release -is | tr '[:upper:]' '[:lower:]') $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list \
+    #
+    # Add the Azure CLI package source
+    && curl -sL https://packages.microsoft.com/keys/microsoft.asc | apt-key add - 2>/dev/null \
+    && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/azure-cli.list \
+    #
+    # Install Packages
+    && apt-get update \
+    && apt-get install -y --no-install-recommends \
+        docker-ce-cli \
+        azure-cli \
+    #
+    # Clean up
+    && apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
+
+# Install Go development tools
+RUN mkdir -p /tmp/gotools \
+    && cd /tmp/gotools \
     #
     # Build Go tools w/module support
-    && mkdir -p /tmp/gotools \
-    && cd /tmp/gotools \
-    && GOPATH=/tmp/gotools GO111MODULE=on go get -v golang.org/x/tools/gopls@latest 2>&1 \
     && GOPATH=/tmp/gotools GO111MODULE=on go get -v \
+        golang.org/x/tools/gopls@latest \
         honnef.co/go/tools/...@latest \
         golang.org/x/tools/cmd/gorename@latest \
         golang.org/x/tools/cmd/goimports@latest \
@@ -86,54 +77,30 @@ RUN apt-get update \
     # Install golangci-lint
     && curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin 2>&1 \
     #
-    # Use Docker script from script library to set things up
-    && curl -sSL $DOCKER_SCRIPT_SOURCE -o /tmp/docker-setup.sh \
-    && ([ "${DOCKER_SCRIPT_SHA}" = "dev-mode" ] || (echo "${DOCKER_SCRIPT_SHA} /tmp/docker-setup.sh" | sha256sum -c -)) \
-    && /bin/bash /tmp/docker-setup.sh "${ENABLE_NONROOT_DOCKER}" "${SOURCE_SOCKET}" "${TARGET_SOCKET}" "${USERNAME}" \
-    && rm /tmp/docker-setup.sh \
-    #
-    # Install kubectl
-    && curl -sSL -o /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
-    && chmod +x /usr/local/bin/kubectl \
-    #
-    # Install Helm
-    && curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash - \
-    #
-    # Install the Azure CLI
-    && apt-get install -y apt-transport-https curl gnupg2 lsb-release \
-    && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/azure-cli.list \
-    && curl -sL https://packages.microsoft.com/keys/microsoft.asc | apt-key add - 2>/dev/null \
-    && apt-get update \
-    && apt-get install -y azure-cli \
-    #
-    # Copy localhost's ~/.kube/config file into the container and swap out localhost
-    # for host.docker.internal whenever a new shell starts to keep them in sync.
-    && echo '\n\
-        if [ "$SYNC_LOCALHOST_KUBECONFIG" == "true" ] && [ -d "/usr/local/share/kube-localhost" ]; then\n\
+    # Clean up
+    && rm -rf /tmp/gotools
+
+# Copy shares from localhost into container when new shells are created
+RUN echo '\n\
+        if [ -d "/usr/local/share/kube-localhost" ]; then\n\
             mkdir -p $HOME/.kube\n\
-            sudo cp -r /usr/local/share/kube-localhost/* $HOME/.kube\n\
-            sudo chown -R $(id -u) $HOME/.kube\n\
+            cp -r /usr/local/share/kube-localhost/* $HOME/.kube\n\
+            chown -R $(id -u) $HOME/.kube\n\
             sed -i -e "s/localhost/host.docker.internal/g" $HOME/.kube/config\n\
         \n\
             if [ -d "/usr/local/share/minikube-localhost" ]; then\n\
                 mkdir -p $HOME/.minikube\n\
-                sudo cp -r /usr/local/share/minikube-localhost/ca.crt $HOME/.minikube\n\
-                sudo cp -r /usr/local/share/minikube-localhost/client.crt $HOME/.minikube\n\
-                sudo cp -r /usr/local/share/minikube-localhost/client.key $HOME/.minikube\n\
-                sudo chown -R $(id -u) $HOME/.minikube\n\
+                cp -r /usr/local/share/minikube-localhost/ca.crt $HOME/.minikube\n\
+                cp -r /usr/local/share/minikube-localhost/client.crt $HOME/.minikube\n\
+                cp -r /usr/local/share/minikube-localhost/client.key $HOME/.minikube\n\
+                chown -R $(id -u) $HOME/.minikube\n\
                 sed -i -r "s|(\s*certificate-authority:\s).*|\\1$HOME\/.minikube\/ca.crt|g" $HOME/.kube/config\n\
                 sed -i -r "s|(\s*client-certificate:\s).*|\\1$HOME\/.minikube\/client.crt|g" $HOME/.kube/config\n\
                 sed -i -r "s|(\s*client-key:\s).*|\\1$HOME\/.minikube\/client.key|g" $HOME/.kube/config\n\
             fi\n\
-        fi' | tee -a /root/.bashrc /root/.zshrc /home/${USERNAME}/.bashrc >> /home/${USERNAME}/.zshrc \
-    #
-    # Clean up
-    && apt-get autoremove -y \
-    && apt-get clean -y \
-    && rm -rf /var/lib/apt/lists/* /tmp/gotools
-
-# Setting the ENTRYPOINT to docker-init.sh will configure non-root access to 
-# the Docker socket if "overrideCommand": false is set in devcontainer.json. 
-# The script will also execute CMD if you need to alter startup behaviors.
-ENTRYPOINT [ "/usr/local/share/docker-init.sh" ]
-CMD [ "sleep", "infinity" ]
+        fi\n\
+        if [ -d "/usr/local/share/azure-localhost" ]; then\n\
+            mkdir -p $HOME/.azure\n\
+            cp -r /usr/local/share/azure-localhost/* $HOME/.azure\n\
+            chown -R $(id -u) $HOME/.azure\n\
+        fi' | tee -a /root/.bashrc /root/.zshrc /home/${USERNAME}/.bashrc >> /home/${USERNAME}/.zshrc
