Run tests of controllers separately

diff --git a/.github/workflows/pr-validation.yml b/.github/workflows/pr-validation.yml
--- a/.github/workflows/pr-validation.yml
+++ b/.github/workflows/pr-validation.yml
@@ -173,6 +173,71 @@ jobs:
       - name: Take Ownership
         run: sudo chown -R $USER:$USER .
 
+  test-controllers:
+    runs-on: [self-hosted, 1ES.Pool=aso-1es-pool]
+    permissions:
+      packages: read
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pinned to 6.0.2
+        with:
+          fetch-depth: 0 # required to access tags
+          submodules: 'true'
+
+      - name: Force docker to SSD
+        run: sudo scripts/v2/linux-docker-use-ssd.sh --containerd true
+
+      - name: check-changes
+        id: check-changes
+        run: scripts/v2/check-changes.sh
+
+      - name: Log in to GitHub Docker Registry
+        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # pinned to v3.7.0
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+        if: steps.check-changes.outputs.code-changed == 'true'
+
+      # Note: Changes to this step must also be mirrored into pr-validation-with-secrets.yaml
+      - name: Build devcontainer image
+        run: |
+          docker build --cache-from ghcr.io/azure/azure-service-operator/aso-devcontainer:latest --tag devcontainer:latest .devcontainer
+        env:
+          DOCKER_BUILDKIT: 1
+        if: steps.check-changes.outputs.code-changed == 'true'
+
+      - name: Run devcontainer image
+        id: devcontainer
+        run: |
+          container_id=$(docker create -w /workspace -v $GITHUB_WORKSPACE:/workspace -v /var/run/docker.sock:/var/run/docker.sock --network=host devcontainer:latest)
+          docker start "$container_id"
+          echo "container_id=$container_id" >> $GITHUB_ENV
+        if: steps.check-changes.outputs.code-changed == 'true'
+
+      - name: Run CI tasks
+        run: |
+          container_id=${{ env.container_id }}
+
+          set +e # don't exit instantly on failure, we need to produce Markdown summary
+          docker exec "$container_id" task controller:test-controllers
+
+          EXIT_CODE=$?
+          set -e
+
+          # generate summary Markdown file for display in Actions
+          cat reports/*.md > $GITHUB_STEP_SUMMARY
+          exit $EXIT_CODE
+        if: steps.check-changes.outputs.code-changed == 'true'
+
+      - name: Save JSON logs on failure
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v4.4.3
+        with:
+          name: test-output
+          path: reports/*.json
+
   test-samples:
     runs-on: [self-hosted, 1ES.Pool=aso-1es-pool]
     permissions:
