Fix no summary for failed runs

diff --git a/.github/workflows/pr-validation.yml b/.github/workflows/pr-validation.yml
--- a/.github/workflows/pr-validation.yml
+++ b/.github/workflows/pr-validation.yml
@@ -94,10 +94,15 @@ jobs:
       - name: Run CI tasks
         run: |
           container_id=${{steps.devcontainer.outputs.id}}
-          docker exec "$container_id" task ci
 
-          # generate summary file for display in Actions
+          set +e # don't exit instantly on failure, we need to produce Markdown summary
+          docker exec "$container_id" task ci
+          EXIT_CODE=$?
+          set -e
+
+          # generate summary Markdown file for display in Actions
           cat reports/*.md > $GITHUB_STEP_SUMMARY
+          exit EXIT_CODE
         
       - name: Build docker image & build configuration YAML
         run: |
